### ISSUE TITLE
Assets are not recreated when running build with --watch flag

### ISSUE THREAD

**Issue by tstehr** [laynezh/vite-plugin-lib-assets#62]
When running `vite build` with the [`--watch` flag](https://vitejs.dev/guide/build.html#rebuild-on-files-changes), the `assets` folder and its contents are not re-created after a rebuild triggered by the watcher.

**Steps to reproduce:**

- Check out [this example project](https://github.com/tstehr/repro-plugin-lib-assets-build-watch) and run `yarn install`
- Run `yarn run vite build --watch` in the project directory
- Observe that a folder `./dist/assets` is created containing the svg linked in `App.tsx`
- Change a file in the project in some way that triggers a rebuild

**Expected:** The `./dist/assets` folder continues to exist and contains the svg

**Actual:** The `./dist/assets` is deleted and the build output is now missing the svg file.

A possible workaround is to set the [`build.emptyOutDir` option](https://vitejs.dev/config/build-options.html#build-emptyoutdir) to `false` so the assets created in the initial build aren't cleared by the rebuild. However, this introduces the risk of stale build outputs being present after the build.

**Comment by coder-layne** [comment]
@tstehr Thanks for your feedback, I'll try to confirm the issue and fix it soon.

**Comment by coder-layne** [comment]
@tstehr I just fixed the issue you encountered and released v0.5.17.

**Comment by vahnag** [comment]
@coder-layne I still experience the same issue with `v0.5.21`. Any idea what could be causing it?

The assets are generated on the initial build. But are failing to generate on watch mode.

**Comment by coder-layne** [comment]
@vahnag Thanks for your feedback, can you provide a minimal reproducible example?

**Comment by vahnag** [comment]
@coder-layne I used @tstehr's reproducible example above and can reproduce it still on that repo.

I upgraded `@laynezh/vite-plugin-lib-assets` to the latest version `0.5.21`.

Whenever you make an edit in `App.tsx` it re-creates the asset imported in that file.
But if you make a change in `main.tsx` no asset is re-created.

In fact, only assets that are imported in the current changed file are being re-created.

So if I add a new asset and import it in `main.tsx` and make a change in that file that asset will get re-created, but the one in App.tsx will get skipped.

**Comment by coder-layne** [comment]
@vahnag The issue you described arises because in v0.5.21, the cache for emitted assets is cleared between rebuilds, and subsequent rebuilds only cache partial assets due to on-demand compilation. In the recently released v0.5.23, the cache will always be preserved.

**Comment by vahnag** [comment]
@coder-layne can confirm the issue is resolved now, thank you for the quick fix!

**Comment by coder-layne** [comment]
@vahnag My pleasure!

**Comment by vahnag** [comment]
@coder-layne this seems be broken on Vite 5.4.14 and on latest 6.

**Comment by coder-layne** [comment]
@vahnag I'll confirm it soon.

**Comment by johnwc** [comment]
Seeing this issue as well

**Comment by ariccadonna** [comment]
Hi, we're still experiencing this issue with version 2.1.0 using vite 7
